import Head from 'next/head'
import Header from "../Components/Header";
import {getSession} from "next-auth/react";
import Login from "../Components/Login";
import SideBar from "../Components/SideBar";
import Feed from "../Components/Feed";

export default function Home({ session }) {
  if (session) return <Login />;
  return (
    <div>
      <Head>
        <title>EventEarth</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


        {/*header*/}
        <Header></Header>

        <main className="flex">
            <SideBar></SideBar>
            {/*sidebar*/}
            <Feed></Feed>
            {/*feed*/}
            {/*widgets*/}
        </main>
    </div>
  )
}

export async function getServerSideProps(context){
  const session= await getSession(context);
  return {
    props: {
      session
    }
  }
}